footnoteReturnLinkContents = "↩"
disqusShortname = "rusticreverie"
title = "Noetic Nought"
enableRobotsTXT = true
SectionPagesMenu = "main"
languageCode = "en-US"
baseurl = "https://punchagan.muse-amuse.in/"
theme = "cocoa-eh"
paginate = 10000
rssLimit = 25
googleAnalytics = "UA-21111013-1"
canonifyURLs = true

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
latestpostcount = 5
hide_author = true
highlightjs = true
powered_by = false
show_menu = true
progressively = true

author = ""
description = ""

logofile = "/images/logo.svg"

copyright = "© 2017"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"

github = "punchagan"
twitter = "punchagan"
email = "punchagan@muse-amuse.in"
goodreads = "58550413-punch"
