footnoteReturnLinkContents = "↩"
title = "Noetic Nought"
description = "Punch's home on the web"
enableRobotsTXT = true
languageCode = "en-US"
baseurl = "https://punchagan.muse-amuse.in/"
theme = "er"
rssLimit = 25
canonifyURLs = true
copyright = "© 2018 CC-BY-SA-4.0"
# pygments
pygmentsCodeFences = true
pygmentsStyle = "emacs"
paginate = 5

[menu]
[[menu.main]]
identifier = "best-posts"
name = "Best posts"
title = "Best posts"
url = "/categories/best/"
weight = -110

[[menu.main]]
identifier = "recurse-center"
name = "recurse-center"
title = "recurse-center"
url = "/recurse-center/"
weight = 10

[params]
mainSections = ["blog"]
dateform = "Jan 2, 2006"
